Cav 574
hmrc/cip-email pull request #12
Opened 2022-11-25 16:58 UTC by mar36tin

2022-11-25 16:59 UTC, johno1985 commented on app/uk/gov/hmrc/cipemail/controllers/InternalAuthAccess.scala
> +    ResourceLocation("")),
should be *

2022-11-25 16:59 UTC, johno1985 commented on app/uk/gov/hmrc/cipemail/controllers/InternalAuthAccess.scala
> +    IAAction("READ"))
should be *

2022-11-25 17:01 UTC, johno1985 requested changes
minor comments and changes required

2022-11-25 17:03 UTC, mar36tin commented on app/uk/gov/hmrc/cipemail/controllers/InternalAuthAccess.scala
> +    IAAction("READ"))
done

2022-11-25 17:06 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/controllers/NotificationControllerSpec.scala
> +      Permission(Resource(ResourceType("cip-email"), ResourceLocation("")), IAAction("READ"))
needs updating else test will fail

2022-11-25 17:06 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/controllers/VerifyControllerSpec.scala
> +      Permission(Resource(ResourceType("cip-email"), ResourceLocation("")), IAAction("READ"))
needs updating else test will fail

2022-11-25 17:06 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/controllers/VerifyPasscodeControllerSpec.scala
> +      Permission(Resource(ResourceType("cip-email"), ResourceLocation("")), IAAction("READ"))
needs updating else test will fail

2022-11-25 17:14 UTC, johno1985 commented
still one last failing unit test, to do with metrics mock

2022-11-25 18:07 UTC, johno1985 approved these changes

2022-12-06 08:53 UTC, johno1985 commented
rebuild

2022-12-06 08:59 UTC, johno1985 commented
unit test failures

2022-12-06 17:37 UTC, johno1985 commented
rebuild

2022-12-07 11:33 UTC, johno1985 approved these changes

2022-12-07 11:33 UTC, merged