CAV-651 - Circuit breaker
hmrc/cip-email pull request #15
Opened 2022-12-12 13:16 UTC by mar36tin

2022-12-12 14:31 UTC, johno1985 commented on it/uk/gov/hmrc/cipemail/VerifyIntegrationSpec.scala
> +//import scala.util.Random
left by mistake?

2022-12-12 14:32 UTC, johno1985 commented on it/uk/gov/hmrc/cipemail/VerifyIntegrationSpec.scala
> +      val emailPrefix = RandomStringUtils.randomAlphabetic(4)
was this needed?

2022-12-12 14:32 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/CircuitBreakerWrapperSpec.scala
> +    implicit class IntToDuration(timeout: Int) {
this block is not needed, see corresponding file in cip-email-verification

2022-12-12 14:33 UTC, johno1985 reviewed
minor comments

2022-12-12 14:34 UTC, mar36tin commented on it/uk/gov/hmrc/cipemail/VerifyIntegrationSpec.scala
> +//import scala.util.Random
yes thanks

2022-12-13 15:33 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    implicit class IntToDuration(timeout: Int) {
block not needed

2022-12-13 15:33 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    when(appConfigMock.verificationConfig).thenReturn(CipVerificationConfig(
use idiomatics

2023-01-25 11:09 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    when(appConfigMock.verificationConfig).thenReturn(CipVerificationConfig(
unresolved comment

2023-01-25 11:09 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    implicit class IntToDuration(timeout: Int) {
unresolved comment

2023-01-25 15:26 UTC, johno1985 commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    when(appConfigMock.verificationConfig).thenReturn(CipVerificationConfig(
still unresolved

2023-01-25 15:26 UTC, johno1985 requested changes
still one unresolved comment

2023-01-26 09:05 UTC, mar36tin commented on test/uk/gov/hmrc/cipemail/connectors/VerifyConnectorSpec.scala
> +    when(appConfigMock.verificationConfig).thenReturn(CipVerificationConfig(
resolved

2023-01-26 09:06 UTC, johno1985 approved these changes

2023-01-26 09:15 UTC, merged